# Exercise - Rollback
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample
              Create an Amazon EC2 instance running the Amazon Linux AMI.'
              
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      InstanceType: t3.micro
      KeyName: new-key-pair
      ImageId: 'ami-036d46416a34a611c'
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0